# Generated by Django 4.2.6 on 2023-10-22 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_groups_remove_employee_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
